apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: list-files
  namespace: mcaruso-test
spec:
  steps:
    - computeResources: {}
      image: 'alpine:latest'
      name: list-files
      script: >
        ls -la $(workspaces.source.path); cat $(workspaces.source.path)/pom.xml;
        cat /workspace/maven-settings/settings.xml
  workspaces:
    - name: source
    - name: maven-settings
