apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines-configuration
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: tekton
    repoURL: 'https://github.com/pacaruso/person-service.git'
    targetRevision: HEAD
  sources: []
  project: default
