apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: build-and-deploy
  namespace: mcaruso-test
spec:
  params:
    - default: 'https://github.com/pacaruso/person-service.git'
      description: Source to the GIT
      name: git-url
      type: string
    - default: main
      description: revision to be used
      name: git-revision
      type: string
    - name: context-dir
      default: "the-source"
      type: string
      description: Where to checkout the source relative to the workspace
    - name: image-name
      type: string
      description: the name of the target image including registry
      default: quay.io/mcaruso/person-service
    - name: image-username
      type: mcaruso
      description: the username you use to access the registry
    - name: image-password
      type: string
      description: The password you use to access the registry
    - name: target-namespace
      description: mcaruso-test
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: 'source'
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:f5206d183e4bdaa90800f349c6cd6a5ee62741dd944fa34e08c44ec0c125869d
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source-workspace
    - name: maven-build-and-push
      params:
        - name: MAVEN_IMAGE
          value: >-
            registry.redhat.io/ubi8/openjdk-17@sha256:e8cc2e476282b75d89c73057bfa713db22d72bdb2808d62d981a84c33beb2575
        - name: GOALS
          value:
            - '-B'
            - '-s'
            - $(workspaces.maven-settings.path)/settings.xml
            - '-Dmaven.repo.local=$(workspaces.source.path)/local_repository'
            - '-DskipTests'
            - '-Dquarkus.container-image.push=true'
            - '-Dquarkus.container-image.build=true'
            - '-Dquarkus.container-image.builder=jib'
            - '-Dquarkus.container-image.image=$(params.image-name)'
            - '-Dquarkus.container-image.username=$(params.image-username)'
            - '-Dquarkus.container-image.password=$(params.image-password)'
            - package
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: SERVER_USER
          value: ''
        - name: SERVER_PASSWORD
          value: ''
        - name: PROXY_USER
          value: ''
        - name: PROXY_PASSWORD
          value: ''
        - name: PROXY_PORT
          value: ''
        - name: PROXY_HOST
          value: ''
        - name: PROXY_NON_PROXY_HOSTS
          value: ''
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: 'source'
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: source-workspace
        - name: maven-settings
          workspace: maven-settings-workspace
  workspaces:
    - name: source-workspace
    - name: maven-settings-workspace
