apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"tekton.dev/v1","kind":"Pipeline","metadata":{"annotations":{},"creationTimestamp":"2024-07-02T10:03:13Z","generation":19,"name":"test-pipeline","namespace":"mcaruso-test","resourceVersion":"539179553","uid":"23c2a01c-8165-46dc-bfbd-789b47c2150e"},"spec":{"tasks":[{"name":"git-clone","params":[{"name":"url","value":"https://github.com/pacaruso/person-service.git"},{"name":"revision","value":"main"},{"name":"refspec","value":""},{"name":"submodules","value":"true"},{"name":"depth","value":"1"},{"name":"sslVerify","value":"true"},{"name":"crtFileName","value":"ca-bundle.crt"},{"name":"subdirectory","value":""},{"name":"sparseCheckoutDirectories","value":""},{"name":"deleteExisting","value":"true"},{"name":"httpProxy","value":""},{"name":"httpsProxy","value":""},{"name":"noProxy","value":""},{"name":"verbose","value":"true"},{"name":"gitInitImage","value":"registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:f5206d183e4bdaa90800f349c6cd6a5ee62741dd944fa34e08c44ec0c125869d"},{"name":"userHome","value":"/home/git"}],"taskRef":{"kind":"ClusterTask","name":"git-clone"},"workspaces":[{"name":"output","workspace":"repository-workspace"}]},{"name":"list-files","runAfter":["git-clone"],"taskRef":{"kind":"Task","name":"list-files"},"workspaces":[{"name":"source","workspace":"repository-workspace"},{"name":"maven-settings","workspace":"maven-settings-workspace"}]},{"name":"maven-build-and-push","params":[{"name":"MAVEN_IMAGE","value":"registry.redhat.io/ubi8/openjdk-17@sha256:e8cc2e476282b75d89c73057bfa713db22d72bdb2808d62d981a84c33beb2575"},{"name":"GOALS","value":["-B","-s","$(workspaces.maven-settings.path)/settings.xml","-Dmaven.repo.local=$(workspaces.source.path)/MAVEN_MIRROR","package"]},{"name":"MAVEN_MIRROR_URL","value":""},{"name":"SERVER_USER","value":""},{"name":"SERVER_PASSWORD","value":""},{"name":"PROXY_USER","value":""},{"name":"PROXY_PASSWORD","value":""},{"name":"PROXY_PORT","value":""},{"name":"PROXY_HOST","value":""},{"name":"PROXY_NON_PROXY_HOSTS","value":""},{"name":"PROXY_PROTOCOL","value":"http"},{"name":"CONTEXT_DIR","value":""}],"runAfter":["list-files"],"taskRef":{"kind":"ClusterTask","name":"maven"},"workspaces":[{"name":"source","workspace":"repository-workspace"},{"name":"maven-settings","workspace":"maven-settings-workspace"}]}],"workspaces":[{"name":"repository-workspace"},{"name":"maven-settings-workspace"}]}}
  creationTimestamp: '2024-07-02T10:03:13Z'
  generation: 20
  managedFields:
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2024-07-02T15:51:51Z'
    - apiVersion: tekton.dev/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          'f:tasks': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2024-07-04T08:54:35Z'
  name: build-and-deploy
  namespace: mcaruso-test
  resourceVersion: '539189385'
  uid: 23c2a01c-8165-46dc-bfbd-789b47c2150e
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/pacaruso/person-service.git'
        - name: revision
          value: main
        - name: refspec
          value: ''
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: subdirectory
          value: ''
        - name: sparseCheckoutDirectories
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: httpProxy
          value: ''
        - name: httpsProxy
          value: ''
        - name: noProxy
          value: ''
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:f5206d183e4bdaa90800f349c6cd6a5ee62741dd944fa34e08c44ec0c125869d
        - name: userHome
          value: /home/git
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: repository-workspace
    - name: list-files
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: list-files
      workspaces:
        - name: source
          workspace: repository-workspace
        - name: maven-settings
          workspace: maven-settings-workspace
    - name: maven-build-and-push
      params:
        - name: MAVEN_IMAGE
          value: >-
            registry.redhat.io/ubi8/openjdk-17@sha256:e8cc2e476282b75d89c73057bfa713db22d72bdb2808d62d981a84c33beb2575
        - name: GOALS
          value:
            - '-B'
            - '-s'
            - $(workspaces.maven-settings.path)/settings.xml
            - '-Dmaven.repo.local=$(workspaces.source.path)/MAVEN_MIRROR'
            - package
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: SERVER_USER
          value: ''
        - name: SERVER_PASSWORD
          value: ''
        - name: PROXY_USER
          value: ''
        - name: PROXY_PASSWORD
          value: ''
        - name: PROXY_PORT
          value: ''
        - name: PROXY_HOST
          value: ''
        - name: PROXY_NON_PROXY_HOSTS
          value: ''
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: ''
      runAfter:
        - list-files
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: repository-workspace
        - name: maven-settings
          workspace: maven-settings-workspace
  workspaces:
    - name: repository-workspace
    - name: maven-settings-workspace
